### ISSUE TITLE
Fix mistake in drush related tasks

### ISSUE THREAD

**Issue by donbuche** [webfer/ansible-drupal#46]
Hi there,

In two tasks, placed at `before-cleanup-tasks.yml` and `after-symlink.yml` there's a little mistake:

```
# Rebuild Drupal cache
- name: Rebuild Drupal cache using Drush
  shell: |
    {{ release_drush_path }}
  args:
    chdir: '{{ release_drupal_path }}'
    executable: /bin/bash
  tags:
    - drupal
```

It should be like the following snippet, including the `cr` command:

```
# Rebuild Drupal cache
- name: Rebuild Drupal cache using Drush
  shell: |
    {{ release_drush_path }} cr
  args:
    chdir: '{{ release_drupal_path }}'
    executable: /bin/bash
  tags:
    - drupal
```
